<?php /* @var $block OsmanSorkar\Themesettings\Block\Categoryfilter */ ?>
<div class="left-sidebar">
    <h2>Category</h2>
    <div class="panel-group category-products" id="accordian"><!--category-productsr-->
        <?php foreach ($block->getCategoryCollection() as $_category){
            if($_category->getChildrenCount()==0){ ?>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title"><a href="<?php echo $_category->getUrl(); ?>"><?php echo $_category->getName(); ?></a></h4>
                    </div>
                </div>
                <?php
                continue;
            }
            $childCategorys=$block->getChildCategory($_category->getId());
            ?>

            <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a data-toggle="collapse" data-parent="#accordian" href="#child_<?php echo $_category->getId() ?>">
                        <span class="badge pull-right"><i class="fa fa-plus"></i></span>
            <?php echo $_category->getName() ?> <?php //echo $_category->getLevel() ?>
                    </a>
                </h4>
            </div>
                <div id="child_<?php echo $_category->getId() ?>" class="panel-collapse collapse">
                    <div class="panel-body">
                        <ul>
                            <?php foreach ($childCategorys as $_childCategory){?>
                            <li><a href="<?php echo $_childCategory->getUrl(); ?>"><?php echo $_childCategory->getName(); ?> </a></li>
                            <?php }?>
                        </ul>
                    </div>
                </div>
            </div>
<?php
    }
?>
    </div><!--/category-products-->
</div>