<?php echo $block->getChildHtml("topbar"); ?>
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
						
						
						
							<?php echo $block->getChildHtml("logo"); ?>
						</div>
<!-- 						<div class="btn-group pull-right">
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									USA
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Canada</a></li>
									<li><a href="#">UK</a></li>
								</ul>
							</div>
							
							<div class="btn-group">
								<button type="button" class="btn btn-default dropdown-toggle usa" data-toggle="dropdown">
									DOLLAR
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu">
									<li><a href="#">Canadian Dollar</a></li>
									<li><a href="#">Pound</a></li>
								</ul>
							</div>
						</div> -->
					</div>
					<div class="col-sm-8">
						<div class="shop-menu pull-right">
						<?php //echo $block->getChildHtml("top.links"); ?>
							<ul class="nav navbar-nav">
								<li><a href="<?php echo $block->getUrl("customer/account"); ?>"><i class="fa fa-user"></i> Account</a></li>
								<li><a href="<?php echo $block->getUrl("wishlist"); ?>"><i class="fa fa-star"></i> Wishlist</a></li>
								<li><a href="<?php echo $block->getUrl("checkout"); ?>"><i class="fa fa-crosshairs"></i> Checkout</a></li>
								<li><a href="<?php echo $block->getUrl("customer/account/login"); ?>"><i class="fa fa-lock"></i> Login</a></li>
								<li><?php echo $block->getChildHtml("minicart"); ?></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-9">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
						
<?php echo $block->getChildHtml("catalog.topnav"); ?>	

</div>
					</div>
					<div class="col-sm-3">
					
						<div class="search_box pull-right">
						<?php echo $block->getChildHtml("topSearch") ?>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->