<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<div class="block d-newsletter single-widget">
    <h2>About Shopper</h2>
        <form class="form d-subscribe searchform"
            novalidate
            action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">

            <button class="action d-subscribe btn btn-default pull-right" title="<?php /* @escapeNotVerified */ echo __('Subscribe') ?>" type="submit">
                   <i class="fa fa-arrow-circle-o-right"></i>
                </button>

                    <input name="email" type="email" id="newsletter"
                                placeholder="<?php /* @escapeNotVerified */ echo __('Enter your email address') ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
 
                
                <div id="newsletter-error"></div>
            <p>Get the most recent updates from <br />our site and be updated your self...</p>
        </form>
        
</div>
