<?php /* @var $block OsmanSorkar\Themesettings\Block\Topbar */ ?>
<div class="header_top"><!--header_top-->
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="contactinfo">
                    <ul class="nav nav-pills">
                        <li><a href="#"><i class="fa fa-phone"></i> <?php echo $block->getPhone(); ?></a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i> <?php echo $block->getEmail(); ?></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="social-icons pull-right">
                    <ul class="nav navbar-nav">
                        <li><a href="<?php echo $block->getSocialUrl("fb"); ?> "><i class="fa fa-facebook"></i></a></li>
                        <li><a href="<?php echo $block->getSocialUrl("tw"); ?>"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="<?php echo $block->getSocialUrl("in"); ?>"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="<?php echo $block->getSocialUrl("dr"); ?>"><i class="fa fa-dribbble"></i></a></li>
                        <li><a href="<?php echo $block->getSocialUrl("fa"); ?>"><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div><!--/header_top-->